version: '3'
services:
  agr_document_classifier:
    build: .
    environment:
      - EMBEDDING_MODEL_PATH=/usr/src/app/embedding_model
      - CLASSIFY_DOCS_DIR=/usr/src/app/classification
      - TRAINING_DOCS_DIR=/usr/src/app/training
      - GROBID_API_URL=${GROBID_API_URL}
      - TOPICS_TO_CLASSIFY=${TOPICS_TO_CLASSIFY}
