FROM python:3.11-slim

ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /usr/src/app
RUN apt-get update && apt-get install --no-install-recommends --yes build-essential git cron
ADD ./requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN python3 -c "import nltk; nltk.download('stopwords'); nltk.download('punkt'); nltk.download('punkt_tab')"
CMD ["/bin/bash"]
