version: '3'
services:
  agr_document_classifier:
    build: .
    volumes:
      - ${TRAINING_DIR}:/data/agr_document_classifier/training
      - ${CLASSIFICATION_DIR}:/data/agr_document_classifier/to_classify
      - ${CLASSIFIERS_PATH}:/data/agr_document_classifier
    environment:
      - GROBID_API_URL=${GROBID_API_URL}
      - TMP_PATH=${TMP_PATH}
      - ABC_API_SERVER=${ABC_API_SERVER}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - OKTA_CLIENT_SECRET=${OKTA_CLIENT_SECRET}
      - OKTA_DOMAIN=${OKTA_DOMAIN}
      - OKTA_AUTH_SERVER_ID=${OKTA_AUTH_SERVER_ID}
      - OKTA_AUDIENCE=${OKTA_AUDIENCE}
      - CLASSIFICATION_BATCH_SIZE=${CLASSIFICATION_BATCH_SIZE}