version: '3'
services:
  agr_automated_information_extraction:
    build: .
    volumes:
      - ${TRAINING_DIR}:/data/agr_document_classifier/training
      - ${CLASSIFICATION_DIR}:/data/agr_document_classifier/to_classify
      - ${CLASSIFIERS_PATH}:/data/agr_document_classifier
      - ${ENTITY_EXTRACTION_DIR}:/data/agr_entity_extraction/to_extract
      - ${AGR_CORPUS_DOWNLOAD_DIR}:${AGR_CORPUS_DOWNLOAD_DIR}
      - ${ENTITY_EXTRACTION_PATH}:/data/agr_entity_extraction
    environment:
      - GROBID_API_URL=${GROBID_API_URL}
      - TMP_PATH=${TMP_PATH}
      - ABC_API_SERVER=${ABC_API_SERVER}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - OKTA_CLIENT_SECRET=${OKTA_CLIENT_SECRET}
      - OKTA_DOMAIN=${OKTA_DOMAIN}
      - OKTA_AUTH_SERVER_ID=${OKTA_AUTH_SERVER_ID}
      - OKTA_AUDIENCE=${OKTA_AUDIENCE}
      - CLASSIFICATION_BATCH_SIZE=${CLASSIFICATION_BATCH_SIZE}
      - AGR_CORPUS_DOWNLOAD_DIR=${AGR_CORPUS_DOWNLOAD_DIR}
