name: Claude Code Review

# IMPORTANT: This workflow automatically runs ONLY when a PR is first opened.
# To request another review after making changes, comment "@claude Please review my changes."

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  claude-review:
    # Only run on pull requests and PR comments (not issue comments)
    if: |
      (github.event_name == 'pull_request' && github.event.action == 'opened') || 
      (github.event_name == 'issue_comment' && github.event.issue.pull_request)
    permissions:
      contents: read
      pull-requests: write
      issues: write
      # REQUIRED: Must grant id-token permission to the reusable workflow
      id-token: write
    uses: alliance-genome/.github/.github/workflows/claude-code-review.yml@main
    with:
      model: claude-sonnet-4-20250514
      max_turns: "60"
      # Python-specific focus for automated information extraction
      review_focus: "critical bugs, performance issues, and data integrity problems in the Python information extraction pipeline. Focus on: memory efficiency, data validation errors, exception handling, regex pattern bugs, parsing logic issues, and potential data loss scenarios"
      trigger_phrase: "@claude"
      # Use centralized threshold from .github repo (skip_threshold: 3)
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}